### PR TITLE
Support a craft.spec file to customize template application

### PR DESCRIPTION
**Pull request by davesteinberg**
Hi again @fcaldera. Here's the other enhancement that I've been working on. It's a bigger conceptual change.

My motivation was two-fold:

1. I want to be able to delete files that create-react-app generates that a template doesn't actually need. For example, I don't usually want to keep App.css, logo.svg, or serviceWorker.js.

1. I want to keep certain files that cra generates in my template repo (so that the repo is, itself, complete), but not copy them over the ones that cra generates when craft runs, so that I'll always get the latest changes/improvements from cra. For example, I usually don't change favicon.ico, index.html, or manifest.json and would prefer to get the latest from cra.

So, with those in mind, I wanted to add a mechanism to control how craft applies a template. I came up with the simplest thing I could: a list of paths and directives:

- **delete** deletes the file or directory from the generated project.
- **ignore** leaves the specified file or directory exactly as generated (or not) by create-react-app. A file or directory with the same name in the template is ignored.
- **replace** copies the file or directory from the template, replacing a generated file or directory with the same name, if one exists.

So, for example:

```
# A sample craft spec

.gitignore: ignore
public: ignore
src/App.css: delete
src/logo.svg: delete
src/serviceWorker.js: delete
```

If you put such a list in a file called `craft.spec`, craft will read it and act accordingly. If there isn't one, it behaves exactly as before. So, by default, package.json is merged; node_modules, package-lock.json, craft.spec, and .git are ignored; and everything else is replaced.

Since I basically invented this out of thin air, I'm not attached to the details, such as the names of the directives, the name of the file, or the syntax. If you like the overall idea but have suggestions, I'm happy to discuss them and update the code.

### CODE REVIEW

**Comment by davesteinberg** [comment]
@fcaldera I saw you invited me to be a collaborator on this project yesterday. Was that intended as an invitation to merge my own PR/commit directly to master? Or would you still like to look at/discuss changes like this one?

**Comment by fedcho** [comment]
@davesteinberg I would like to discuss big changes and features but also give you the change to integrate them right away. So feel free to do it!

For this one in particular, I think is a great idea and important feature to have. About the syntax maybe you can consider `.yml` so we can have blocks that define the actions to take for each file like:

```yaml
ignore:
    - .gitignore
    - public
delete:
    - src/App.css
    - src/logo.svg
    - src/serviceWorker.js
```

Just a matter of flavor though. It's also fine as it is.

**Comment by davesteinberg** [comment]
@fcaldera Thanks for the suggestion! I really like the idea of using YAML. It gives us flexibility to add more things in the future, and I think the syntax you suggested is easier for the user to understand. So, I added a new commit that switches to that approach.

Internally, I'm converting the structure read from the YAML into the same structure I had before, since keying by the file path makes it easy to have and override defaults.

I'm supporting both .yaml and .yml extensions, since both are very common. I'm also reporting expected value types (e.g. objects).

What do you think? Oh, also, once we're done with this, would you mind publishing a new version on npm?

**Comment by davesteinberg** [comment]
I've been too busy with other things, but I just took another look at my changes, and I'm going to merge them. They're working well for me.

@fcaldera What do you think about publishing a new version on npm?

**Comment by fedcho** [comment]
Hi @davesteinberg. Thanks! I've released the changes as 0.3.0 version to npm. Also invited you as a maintainer so you can release it too. 🎉

**Pull request merged**
